#!/bin/env/python

import os
import sys
import subprocess
import shlex


def main(args):
    filename, extention = args[1].split(".")

    if extention == "md":
        pandoc = shlex.split("pandoc {0}.md -t latex".format(filename))
        tex_txt = subprocess.run(pandoc, stdout=subprocess.PIPE).stdout.decode("utf-8")

    else:
        print("Please input md file")
        sys.exit()

    try:
        template = os.environ["MDTEX"]
    except KeyError:
        print("Please set the value to environment variable MDTEX.\n\
    e.g.)$export MDTEX=template file path")
        sys.exit()

    with open(template, "r") as tf:
        with open(filename+".tex", "w") as wf:
            txt = tex_txt
            txt = txt.replace("\\tightlist", "")
            txt = txt.replace(
                "\\begin{verbatim}", "\\begin{lstlisting}")
            txt = txt.replace("\\end{verbatim}", "\\end{lstlisting}")

            temp = tf.read()
            temp = temp.replace("<<REPLACE_POINT>>", txt)

            wf.write(temp)


if __name__ == "__main__":
    args = sys.argv
    main(args)
