#!/bin/sh

tp(){
	platex $data.tex && \
	platex $data.tex && \
	dvipdfmx $data.dvi
}

tpo(){
	platex $data.tex && \
	platex $data.tex && \
	dvipdfmx $data.dvi

	open $data.pdf
}

if [ "$1" = "" ]; then
    echo "No argument"

else

    getopts "n" opts

    if [ $opts = "n" ]; then
    	data=`basename $2 .tex`

    	tp

    else
        data=`basename $1 .tex`

    	tpo

    fi
fi
